ALTER TABLE clientes_ref 
ADD COLUMN telefone VARCHAR(20) NULL,
ADD COLUMN cpf VARCHAR(11) NULL,
ADD COLUMN data_nascimento DATE NULL,
ADD COLUMN ativo BOOLEAN NULL,
ADD COLUMN erp_updated_at TIMESTAMP NULL;