org.gradle.java.home=/var/lib/flatpak/app/com.google.AndroidStudio/x86_64/stable/1e94aa8fff825492c6f8001c5c0d35d2d2a203edf128eb2ecb3711841b3aea12/files/extra/jbr
android.useAndroidX=true
android.enableJetifier=true

RELEASE_STORE_FILE=/home/gregorio/keystores/monica.jks
RELEASE_STORE_PASSWORD=kKryptz123
RELEASE_KEY_ALIAS=monica
RELEASE_KEY_PASSWORD=kKryptz123
