<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.portalfiscal.inf.br/nfe" 
           xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           targetNamespace="http://www.portalfiscal.inf.br/nfe" 
           elementFormDefault="qualified" 
           attributeFormDefault="unqualified">
    
    <!-- Importa o arquivo que contém a definição do tipo TEnviNFe -->
    <xs:include schemaLocation="leiauteNFe_v4.00.xsd"/>
    
    <!-- Declara o elemento enviNFe explicitamente -->
    <xs:element name="enviNFe" type="TEnviNFe">
        <xs:annotation>
            <xs:documentation>Schema XML de validação do enviNFe</xs:documentation>
        </xs:annotation>
    </xs:element>
</xs:schema>
